=== SnigdhaAthaiya/DFAS/AsyncDataAnalyzer/AsyncDataAnalyzer/dat/SPEC.dtd
<!ELEMENT SPEC (MODULE+)>
<!ELEMENT MODULE (PROCTYPE|MTYPE|INIT)>
<!ELEMENT PROCTYPE (NAME , SEQUENCE)>
<!ELEMENT INIT (SEQUENCE)>
<!ELEMENT MTYPE (NAME+)>
<!ELEMENT SEQUENCE (STEP+)>
<!ELEMENT STEP (STMT | DECLLIST)>
<!ELEMENT DECLLIST (DECL+)>
<!ELEMENT DECL (TYPENAME, IVAR)>
<!ELEMENT TYPENAME (BIT | BOOL | NUM)>
<!ELEMENT BIT EMPTY>
<!ELEMENT BOOL EMPTY>
<!ELEMENT NUM EMPTY>
<!ELEMENT IVAR (NAME, (INDEX)?) >
<!ELEMENT VARREF (NAME, (EXPR | PROPACCESS)?)>
<!ELEMENT PROPACCESS (VARREF)>
<!ELEMENT SEND (NAME)>
<!ELEMENT RECEIVE (NAME)>
<!ELEMENT ASSIGN (VARREF, EXPR)>
<!ELEMENT EXPR ((VARREF | CONST), (OP, (VARREF | CONST))? )>
<!ELEMENT CONST EMPTY>
<!ELEMENT OP EMPTY>
<!ELEMENT NAME EMPTY>
<!ELEMENT INDEX EMPTY>
<!ELEMENT STMT (IF | DO | SEND | RECEIVE | ASSIGN | ELSE | BREAK | GOTO | LABELEDST | ASSERT | EXPR | ATOMIC)>
<!ELEMENT IF ((OPTION)+, (ELSE)?)>
<!ELEMENT DO ((OPTION)+, (ELSE)?)>
<!ELEMENT OPTION (SEQUENCE)>
<!ELEMENT ATOMIC (SEQUENCE)>
<!ELEMENT ELSE (SEQUENCE)>
<!ELEMENT BREAK EMPTY>
<!ELEMENT GOTO (NAME)>
<!ELEMENT LABELEDST (NAME)>
<!ELEMENT ASSERT (EXPR)>

<!ATTLIST CONST VALUE CDATA #REQUIRED>
<!ATTLIST OP VALUE CDATA #REQUIRED>
<!ATTLIST NAME VALUE CDATA #REQUIRED>
<!ATTLIST CONST VALUE CDATA #REQUIRED>
<!ATTLIST ASSIGN VARUSE CDATA #IMPLIED>
<!ATTLIST OPTION VARUSE CDATA #IMPLIED>
<!ATTLIST ASSERT VARUSE CDATA #IMPLIED>
<!ATTLIST ASSIGN LABEL CDATA "DEFAULTLABEL">
<!ATTLIST ASSERT LABEL CDATA "DEFAULTLABEL">
<!ATTLIST OPTION LABEL CDATA "DEFAULTLABEL">
<!ATTLIST ASSERT EVAL (TRUE|FALSE) "FALSE">
<!ATTLIST ASSIGN EVAL (TRUE|FALSE) "FALSE">

=== SnigdhaAthaiya/DFAS/AsyncDataAnalyzer/AsyncDataAnalyzer/test/test2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SPEC SYSTEM "../dat/SPEC.dtd">
<SPEC>
	<MODULE>
		<MTYPE>
			<NAME VALUE="M1" />
		</MTYPE>
	</MODULE>
	<MODULE>
		<PROCTYPE>
			<NAME VALUE="P1" />
			<SEQUENCE>
				<STEP>
					<DECLLIST>
						<DECL>
							<TYPENAME>
								<NUM />
							</TYPENAME>
							<IVAR>
								<NAME VALUE="VAR1" />
							</IVAR>
						</DECL>
					</DECLLIST>
				</STEP>
				<STEP>
					<STMT>
						<ASSIGN>
							<VARREF>
								<NAME VALUE="VAR1" />
							</VARREF>
							<EXPR>
								<VARREF>
									<NAME VALUE="1,0" />
								</VARREF>
							</EXPR>
						</ASSIGN>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<DO>
							<OPTION>
								<SEQUENCE>
									<STEP>
										<STMT>
											<RECEIVE>
												<NAME VALUE="M1" />
											</RECEIVE>
										</STMT>
									</STEP>
									<STEP>
										<STMT>
											<ASSIGN EVAL="TRUE" LABEL="L1" VARUSE="VAR1">
												<VARREF>
													<NAME VALUE="VAR1" />
												</VARREF>
												<EXPR>
													<VARREF>
														<NAME VALUE="1,VAR1" />
													</VARREF>
													<OP VALUE="+" />
													<VARREF>
														<NAME VALUE="1,1" />
													</VARREF>
												</EXPR>
											</ASSIGN>
										</STMT>
									</STEP>

								</SEQUENCE>
							</OPTION>
							<OPTION>
								<SEQUENCE>
									<STEP>
										<STMT>
											<BREAK />
										</STMT>
									</STEP>
								</SEQUENCE>
							</OPTION>
						</DO>
					</STMT>
				</STEP>
			</SEQUENCE>
		</PROCTYPE>
	</MODULE>
</SPEC>
