=== SnigdhaAthaiya/DFAS/AsyncDataAnalyzer/AsyncDataAnalyzer/dat/SPEC.dtd
<!ELEMENT SPEC (MODULE+)>
<!ELEMENT MODULE (PROCTYPE|MTYPE|INIT)>
<!ELEMENT PROCTYPE (NAME , SEQUENCE)>
<!ELEMENT INIT (SEQUENCE)>
<!ELEMENT MTYPE (NAME+)>
<!ELEMENT SEQUENCE (STEP+)>
<!ELEMENT STEP (STMT | DECLLIST)>
<!ELEMENT DECLLIST (DECL+)>
<!ELEMENT DECL (TYPENAME, IVAR)>
<!ELEMENT TYPENAME (BIT | BOOL | NUM)>
<!ELEMENT BIT EMPTY>
<!ELEMENT BOOL EMPTY>
<!ELEMENT NUM EMPTY>
<!ELEMENT IVAR (NAME, (INDEX)?) >
<!ELEMENT VARREF (NAME, (EXPR | PROPACCESS)?)>
<!ELEMENT PROPACCESS (VARREF)>
<!ELEMENT SEND (NAME)>
<!ELEMENT RECEIVE (NAME)>
<!ELEMENT ASSIGN (VARREF, EXPR)>
<!ELEMENT EXPR ((VARREF | CONST), (OP, (VARREF | CONST))? )>
<!ELEMENT CONST EMPTY>
<!ELEMENT OP EMPTY>
<!ELEMENT NAME EMPTY>
<!ELEMENT INDEX EMPTY>
<!ELEMENT STMT (IF | DO | SEND | RECEIVE | ASSIGN | ELSE | BREAK | GOTO | LABELEDST | ASSERT | EXPR | ATOMIC)>
<!ELEMENT IF ((OPTION)+, (ELSE)?)>
<!ELEMENT DO ((OPTION)+, (ELSE)?)>
<!ELEMENT OPTION (SEQUENCE)>
<!ELEMENT ATOMIC (SEQUENCE)>
<!ELEMENT ELSE (SEQUENCE)>
<!ELEMENT BREAK EMPTY>
<!ELEMENT GOTO (NAME)>
<!ELEMENT LABELEDST (NAME)>
<!ELEMENT ASSERT (EXPR)>

<!ATTLIST CONST VALUE CDATA #REQUIRED>
<!ATTLIST OP VALUE CDATA #REQUIRED>
<!ATTLIST NAME VALUE CDATA #REQUIRED>
<!ATTLIST CONST VALUE CDATA #REQUIRED>
<!ATTLIST ASSIGN VARUSE CDATA #IMPLIED>
<!ATTLIST OPTION VARUSE CDATA #IMPLIED>
<!ATTLIST ASSERT VARUSE CDATA #IMPLIED>
<!ATTLIST ASSIGN LABEL CDATA "DEFAULTLABEL">
<!ATTLIST ASSERT LABEL CDATA "DEFAULTLABEL">
<!ATTLIST OPTION LABEL CDATA "DEFAULTLABEL">
<!ATTLIST ASSERT EVAL (TRUE|FALSE) "FALSE">
<!ATTLIST ASSIGN EVAL (TRUE|FALSE) "FALSE">

=== SnigdhaAthaiya/DFAS/AsyncDataAnalyzer/AsyncDataAnalyzer/test/ruaneModel.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SPEC SYSTEM "../dat/SPEC.dtd">
<SPEC>
	<MODULE>
		<MTYPE>
			<NAME VALUE="LK0C" />
			<NAME VALUE="LK0S" />
			<NAME VALUE="LK1C" />
			<NAME VALUE="LK1S" />
			<NAME VALUE="RWANT0" />
			<NAME VALUE="RWANT1" />
			<NAME VALUE="RLOCK0" />
			<NAME VALUE="RLOCK1" />
			<NAME VALUE="STATEWAKE" />
			<NAME VALUE="STATERUN" />
			<NAME VALUE="SLEEP0" />
			<NAME VALUE="SLEEP1" />
			<NAME VALUE="RLOCK0ACK" />
			<NAME VALUE="RLOCK1ACK" />
		</MTYPE>
	</MODULE>

	<MODULE>
		<PROCTYPE>
			<NAME VALUE="START" />
			<SEQUENCE>
				<STEP>
					<STMT>
						<ATOMIC>
							<SEQUENCE>
								<STEP>
									<STMT>
										<SEND>
											<NAME VALUE="LK0C" />
										</SEND>
									</STMT>
								</STEP>
								<STEP>
									<STMT>
										<SEND>
											<NAME VALUE="LK0S" />
										</SEND>
									</STMT>
								</STEP>
							</SEQUENCE>
						</ATOMIC>
					</STMT>
				</STEP>
			</SEQUENCE>
		</PROCTYPE>
	</MODULE>
	<MODULE>
		<PROCTYPE>
			<NAME VALUE="CLIENT" />
			<SEQUENCE>
				<STEP>
					<DECLLIST>
						<DECL>
							<TYPENAME>
								<NUM />
							</TYPENAME>
							<IVAR>
								<NAME VALUE="RLOCK" />
							</IVAR>
						</DECL>
					</DECLLIST>
				</STEP>
				<STEP>
					<STMT>
						<LABELEDST>
							<NAME VALUE="SLEEP" />
						</LABELEDST>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<ATOMIC>
							<SEQUENCE>
								<STEP>
									<STMT>
										<RECEIVE>
											<NAME VALUE="LK0C" />
										</RECEIVE>
									</STMT>
								</STEP>
								<STEP>
									<STMT>
										<SEND>
											<NAME VALUE="LK1C" />
										</SEND>
									</STMT>
								</STEP>
								<STEP>
									<STMT>
										<SEND>
											<NAME VALUE="LK1S" />
										</SEND>
									</STMT>
								</STEP>
							</SEQUENCE>
						</ATOMIC>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<DO>
							<OPTION>
								<SEQUENCE>
									<STEP>
										<STMT>
											<ATOMIC>
												<SEQUENCE>
													<STEP>
														<STMT>
															<RECEIVE>
																<NAME VALUE="RLOCK1" />
															</RECEIVE>
														</STMT>
													</STEP>
													<STEP>
														<STMT>
															<ASSIGN EVAL="TRUE" VARUSE="RLOCK" LABEL="L1">
																<VARREF>
																	<NAME VALUE="RLOCK" />
																</VARREF>
																<EXPR>
																	<VARREF>
																		<NAME VALUE="1,1" />
																	</VARREF>
																</EXPR>
															</ASSIGN>
														</STMT>
													</STEP>
												</SEQUENCE>
											</ATOMIC>
										</STMT>
									</STEP>
									<STEP>
										<STMT>
											<SEND>
												<NAME VALUE="RWANT1" />
											</SEND>
										</STMT>
									</STEP>
									<STEP>
										<STMT>
											<SEND>
												<NAME VALUE="STATEWAKE" />
											</SEND>
										</STMT>
									</STEP>
									<STEP>
										<STMT>
											<ATOMIC>
												<SEQUENCE>
													<STEP>
														<STMT>
															<SEND>
																<NAME VALUE="LK0C" />
															</SEND>
														</STMT>
													</STEP>
													<STEP>
														<STMT>
															<SEND>
																<NAME VALUE="LK0S" />
															</SEND>
														</STMT>
													</STEP>
												</SEQUENCE>
											</ATOMIC>
										</STMT>
									</STEP>
									<STEP>
										<STMT>
											<RECEIVE>
												<NAME VALUE="STATERUN" />
											</RECEIVE>
										</STMT>
									</STEP>
								</SEQUENCE>
							</OPTION>
							<OPTION>
								<SEQUENCE>
									<STEP>
										<STMT>
											<ATOMIC>
												<SEQUENCE>
													<STEP>
														<STMT>
															<RECEIVE>
																<NAME VALUE="RLOCK0" />
															</RECEIVE>
														</STMT>
													</STEP>
												</SEQUENCE>
											</ATOMIC>
										</STMT>
									</STEP>
									<STEP>
										<STMT>
											<BREAK />
										</STMT>
									</STEP>
								</SEQUENCE>
							</OPTION>
						</DO>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<LABELEDST>
							<NAME VALUE="PROGRESS" />
						</LABELEDST>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<ASSERT EVAL="TRUE" VARUSE="RLOCK" LABEL="L2">
							<EXPR>
								<VARREF>
									<NAME VALUE="RLOCK" />
								</VARREF>
								<OP VALUE="==" />
								<CONST VALUE="0" />
							</EXPR>
						</ASSERT>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<ATOMIC>
							<SEQUENCE>
								<STEP>
									<STMT>
										<ASSIGN EVAL="TRUE" VARUSE="RLOCK" LABEL="L3">
											<VARREF>
												<NAME VALUE="RLOCK" />
											</VARREF>
											<EXPR>
												<VARREF>
													<NAME VALUE="1,1" />
												</VARREF>
											</EXPR>
										</ASSIGN>
									</STMT>
								</STEP>
								<STEP>
									<STMT>
										<SEND>
											<NAME VALUE="RLOCK1" />
										</SEND>
									</STMT>
								</STEP>
							</SEQUENCE>
						</ATOMIC>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<ATOMIC>
							<SEQUENCE>
								<STEP>
									<STMT>
										<SEND>
											<NAME VALUE="LK0C" />
										</SEND>
									</STMT>
								</STEP>
								<STEP>
									<STMT>
										<SEND>
											<NAME VALUE="LK0S" />
										</SEND>
									</STMT>
								</STEP>
							</SEQUENCE>
						</ATOMIC>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<GOTO>
							<NAME VALUE="SLEEP" />
						</GOTO>
					</STMT>
				</STEP>
			</SEQUENCE>
		</PROCTYPE>
	</MODULE>

	<MODULE>
		<PROCTYPE>
			<NAME VALUE="SERVER" />
			<SEQUENCE>
				<STEP>
					<STMT>
						<LABELEDST>
							<NAME VALUE="WAKEUP" />
						</LABELEDST>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<ATOMIC>
							<SEQUENCE>
								<STEP>
									<STMT>
										<ASSIGN EVAL="TRUE" VARUSE="RLOCK" LABEL="L4">
											<VARREF>
												<NAME VALUE="RLOCK" />
											</VARREF>
											<EXPR>
												<VARREF>
													<NAME VALUE="1,0" />
												</VARREF>
											</EXPR>
										</ASSIGN>
									</STMT>
								</STEP>
								<STEP>
									<STMT>
										<SEND>
											<NAME VALUE="RLOCK0" />
										</SEND>
									</STMT>
								</STEP>
							</SEQUENCE>
						</ATOMIC>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<RECEIVE>
							<NAME VALUE="LK0S" />
						</RECEIVE>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<IF>
							<OPTION>
								<SEQUENCE>
									<STEP>
										<STMT>
											<RECEIVE>
												<NAME VALUE="RWANT1" />
											</RECEIVE>
										</STMT>
									</STEP>
									<STEP>
										<STMT>
											<ATOMIC>
												<SEQUENCE>
													<STEP>
														<STMT>
															<RECEIVE>
																<NAME VALUE="SLEEP0" />
															</RECEIVE>
														</STMT>
													</STEP>
													<STEP>
														<STMT>
															<SEND>
																<NAME VALUE="SLEEP1" />
															</SEND>
														</STMT>
													</STEP>
												</SEQUENCE>
											</ATOMIC>
										</STMT>
									</STEP>
									<STEP>
										<STMT>
											<SEND>
												<NAME VALUE="RWANT0" />
											</SEND>
										</STMT>
									</STEP>
									<STEP>
										<STMT>
											<RECEIVE>
												<NAME VALUE="LK0S" />
											</RECEIVE>
										</STMT>
									</STEP>
									<STEP>
										<STMT>
											<IF>
												<OPTION>
													<SEQUENCE>
														<STEP>
															<STMT>
																<RECEIVE>
																	<NAME VALUE="STATEWAKE" />
																</RECEIVE>
															</STMT>
														</STEP>
														<STEP>
															<STMT>
																<SEND>
																	<NAME VALUE="STATERUN" />
																</SEND>
															</STMT>
														</STEP>
													</SEQUENCE>
												</OPTION>
												<OPTION>
													<SEQUENCE>
														<STEP>
															<STMT>
																<RECEIVE>
																	<NAME VALUE="STATERUN" />
																</RECEIVE>
															</STMT>
														</STEP>
														<STEP>
															<STMT>
																<EXPR>
																	<CONST VALUE="1" />
																</EXPR>
															</STMT>
														</STEP>
													</SEQUENCE>
												</OPTION>
											</IF>
										</STMT>
									</STEP>
									<STEP>
										<STMT>
											<SEND>
												<NAME VALUE="SLEEP0" />
											</SEND>
										</STMT>
									</STEP>
								</SEQUENCE>
							</OPTION>
							<OPTION>
								<SEQUENCE>
									<STEP>
										<STMT>
											<RECEIVE>
												<NAME VALUE="RWANT0" />
											</RECEIVE>
										</STMT>
									</STEP>
									<STEP>
										<STMT>
											<EXPR>
												<CONST VALUE="1" />
											</EXPR>
										</STMT>
									</STEP>
								</SEQUENCE>
							</OPTION>
						</IF>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<GOTO>
							<NAME VALUE="WAKEUP" />
						</GOTO>
					</STMT>
				</STEP>
			</SEQUENCE>
		</PROCTYPE>
	</MODULE>

</SPEC>

=== SnigdhaAthaiya/DFAS/AsyncDataAnalyzer/AsyncDataAnalyzer/oldModels/jobqueue_test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SPEC SYSTEM "../dat/SPEC.dtd">
<SPEC>
	<MODULE>
		<MTYPE>
			<NAME VALUE="STARTJOB" />
			<NAME VALUE="STARTWORKER" />
			<NAME VALUE="DONE" />
			<NAME VALUE="QUITWORKER1" />
			<NAME VALUE="WORKERSTOP1" />
			<NAME VALUE="QUITWORKER2" />
			<NAME VALUE="WORKERSTOP2" />
			<NAME VALUE="STARTJOBQ" />
			<NAME VALUE="STOPJOBQ" />
			<NAME VALUE="JOBQSTOPPED" />
		</MTYPE>
	</MODULE>
	<MODULE>
		<PROCTYPE>
			<NAME VALUE="TEST" />
			<SEQUENCE>
				<STEP>
					<DECLLIST>
						<DECL>
							<TYPENAME>
								<NUM />
							</TYPENAME>
							<IVAR>
								<NAME VALUE="COUNT" />
							</IVAR>
						</DECL>
					</DECLLIST>
				</STEP>
				<STEP>
					<STMT>
						<ASSIGN>
							<VARREF>
								<NAME VALUE="COUNT" />
							</VARREF>
							<EXPR>
								<VARREF>
									<NAME VALUE="1,0" />
								</VARREF>
							</EXPR>
						</ASSIGN>
					</STMT>
				</STEP>
				<!-- STARTING JOB QUEUE -->
				<STEP>
					<STMT>
						<SEND>
							<NAME VALUE="STARTJOBQ" />
						</SEND>
					</STMT>
				</STEP>

				<!-- STARTING 4 JOBS FOR 2 WORKERS -->
				<STEP>
					<STMT>
						<SEND>
							<NAME VALUE="STARTJOB" />
						</SEND>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<SEND>
							<NAME VALUE="STARTJOB" />
						</SEND>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<SEND>
							<NAME VALUE="STARTJOB" />
						</SEND>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<SEND>
							<NAME VALUE="STARTJOB" />
						</SEND>
					</STMT>
				</STEP>
				
				<!-- STOPPING THE JOB QUEUE -->
				<STEP>
					<STMT>
						<SEND>
							<NAME VALUE="STOPJOBQ" />
						</SEND>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<RECEIVE>
							<NAME VALUE="JOBQSTOPPED" />
						</RECEIVE>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<ASSERT EVAL="TRUE" VARUSE="COUNT" LABEL="L1">
							<EXPR>
								<VARREF>
									<NAME VALUE="COUNT" />
								</VARREF>
								<OP VALUE="==" />
								<CONST VALUE="4" />
							</EXPR>
						</ASSERT>
					</STMT>
				</STEP>
			</SEQUENCE>
		</PROCTYPE>
	</MODULE>



	<MODULE>
		<PROCTYPE>
			<NAME VALUE="WORKER1" />
			<SEQUENCE>
				<STEP>
					<STMT>
						<DO>
							<OPTION>
								<SEQUENCE>
									<STEP>
										<STMT>
											<ATOMIC>
												<SEQUENCE>
													<STEP>
														<STMT>
															<RECEIVE>
																<NAME VALUE="STARTWORKER" />
															</RECEIVE>
														</STMT>
													</STEP>
													<STEP>
														<STMT>
															<ASSIGN EVAL="TRUE" VARUSE="COUNT" LABEL="L2">
																<VARREF>
																	<NAME VALUE="COUNT" />
																</VARREF>
																<EXPR>
																	<VARREF>
																		<NAME VALUE="1,COUNT" />
																	</VARREF>
																	<OP VALUE="+" />
																	<VARREF>
																		<NAME VALUE="1,1" />
																	</VARREF>
																</EXPR>
															</ASSIGN>
														</STMT>
													</STEP>
													<STEP>
														<STMT>
															<SEND>
																<NAME VALUE="DONE" />
															</SEND>
														</STMT>
													</STEP>
												</SEQUENCE>
											</ATOMIC>
										</STMT>
									</STEP>

								</SEQUENCE>
							</OPTION>
							<OPTION>
								<SEQUENCE>
									<STEP>
										<STMT>
											<RECEIVE>
												<NAME VALUE="QUITWORKER1" />
											</RECEIVE>
										</STMT>
									</STEP>
									<STEP>
										<STMT>
											<SEND>
												<NAME VALUE="WORKERSTOP1" />
											</SEND>
										</STMT>
									</STEP>
									<STEP>
										<STMT>
											<BREAK />
										</STMT>
									</STEP>
								</SEQUENCE>
							</OPTION>
						</DO>
					</STMT>
				</STEP>
			</SEQUENCE>
		</PROCTYPE>
	</MODULE>


	<MODULE>
		<PROCTYPE>
			<NAME VALUE="WORKER2" />
			<SEQUENCE>
				<STEP>
					<STMT>
						<DO>
							<OPTION>
								<SEQUENCE>
									<STEP>
										<STMT>
											<ATOMIC>
												<SEQUENCE>
													<STEP>
														<STMT>
															<RECEIVE>
																<NAME VALUE="STARTWORKER" />
															</RECEIVE>
														</STMT>
													</STEP>
													<STEP>
														<STMT>
															<ASSIGN EVAL="TRUE" VARUSE="COUNT" LABEL="L3">
																<VARREF>
																	<NAME VALUE="COUNT" />
																</VARREF>
																<EXPR>
																	<VARREF>
																		<NAME VALUE="1,COUNT" />
																	</VARREF>
																	<OP VALUE="+" />
																	<VARREF>
																		<NAME VALUE="1,1" />
																	</VARREF>
																</EXPR>
															</ASSIGN>
														</STMT>
													</STEP>
													<STEP>
														<STMT>
															<SEND>
																<NAME VALUE="DONE" />
															</SEND>
														</STMT>
													</STEP>
												</SEQUENCE>
											</ATOMIC>
										</STMT>
									</STEP>

								</SEQUENCE>
							</OPTION>
							<OPTION>
								<SEQUENCE>
									<STEP>
										<STMT>
											<RECEIVE>
												<NAME VALUE="QUITWORKER2" />
											</RECEIVE>
										</STMT>
									</STEP>
									<STEP>
										<STMT>
											<SEND>
												<NAME VALUE="WORKERSTOP2" />
											</SEND>
										</STMT>
									</STEP>
									<STEP>
										<STMT>
											<BREAK />
										</STMT>
									</STEP>
								</SEQUENCE>
							</OPTION>
						</DO>
					</STMT>
				</STEP>
			</SEQUENCE>
		</PROCTYPE>
	</MODULE>

	<MODULE>
		<PROCTYPE>
			<NAME VALUE="JOBQ" />
			<SEQUENCE>
				<STEP>
					<STMT>
						<RECEIVE>
							<NAME VALUE="STARTJOBQ" />
						</RECEIVE>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<DO>
							<OPTION>
								<SEQUENCE>
									<STEP>
										<STMT>
											<RECEIVE>
												<NAME VALUE="STARTJOB" />
											</RECEIVE>
										</STMT>
									</STEP>
									<STEP>
										<STMT>
											<SEND>
												<NAME VALUE="STARTWORKER" />
											</SEND>
										</STMT>
									</STEP>
								</SEQUENCE>
							</OPTION>
							<OPTION>
								<SEQUENCE>
									<STEP>
										<STMT>
											<RECEIVE>
												<NAME VALUE="STOPJOBQ" />
											</RECEIVE>
										</STMT>
									</STEP>
									<!-- WAIT FOR THE JOBS TO FINSH FIRST -->
									<STEP>
										<STMT>
											<RECEIVE>
												<NAME VALUE="DONE" />
											</RECEIVE>
										</STMT>
									</STEP>
									<STEP>
										<STMT>
											<RECEIVE>
												<NAME VALUE="DONE" />
											</RECEIVE>
										</STMT>
									</STEP>
									<STEP>
										<STMT>
											<RECEIVE>
												<NAME VALUE="DONE" />
											</RECEIVE>
										</STMT>
									</STEP>
									<STEP>
										<STMT>
											<RECEIVE>
												<NAME VALUE="DONE" />
											</RECEIVE>
										</STMT>
									</STEP>
									
									<!-- NOW STOP ALL WORKERS -->
									<STEP>
										<STMT>
											<SEND>
												<NAME VALUE="QUITWORKER1" />
											</SEND>
										</STMT>
									</STEP>
									<STEP>
										<STMT>
											<SEND>
												<NAME VALUE="QUITWORKER2" />
											</SEND>
										</STMT>
									</STEP>
									<STEP>
										<STMT>
											<RECEIVE>
												<NAME VALUE="WORKERSTOP1" />
											</RECEIVE>
										</STMT>
									</STEP>
									<STEP>
										<STMT>
											<RECEIVE>
												<NAME VALUE="WORKERSTOP2" />
											</RECEIVE>
										</STMT>
									</STEP>
									<STEP>
										<STMT>
											<SEND>
												<NAME VALUE="JOBQSTOPPED" />
											</SEND>
										</STMT>
									</STEP>

								</SEQUENCE>
							</OPTION>

						</DO>
					</STMT>
				</STEP>
			</SEQUENCE>
		</PROCTYPE>
	</MODULE>
</SPEC>

=== SnigdhaAthaiya/DFAS/AsyncDataAnalyzer/AsyncDataAnalyzer/test/test6.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SPEC SYSTEM "../dat/SPEC.dtd">
<SPEC>
	<MODULE>
		<MTYPE>
			<NAME VALUE="M1" />
			<NAME VALUE="M2" />
		</MTYPE>
	</MODULE>
	<MODULE>
		<PROCTYPE>
			<NAME VALUE="P1" />
			<SEQUENCE>
				<STEP>
					<DECLLIST>
						<DECL>
							<TYPENAME>
								<NUM />
							</TYPENAME>
							<IVAR>
								<NAME VALUE="VAR1" />
							</IVAR>
						</DECL>
						<DECL>
							<TYPENAME>
								<NUM />
							</TYPENAME>
							<IVAR>
								<NAME VALUE="VAR2" />
							</IVAR>
						</DECL>
					</DECLLIST>
				</STEP>
				<STEP>
					<STMT>
						<ASSIGN>
							<VARREF>
								<NAME VALUE="VAR1" />
							</VARREF>
							<EXPR>
								<VARREF>
									<NAME VALUE="1,3" />
								</VARREF>
							</EXPR>
						</ASSIGN>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<SEND>
							<NAME VALUE="M1" />
						</SEND>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<ASSERT>
							<EXPR>
								<VARREF>
									<NAME VALUE="VAR" />
								</VARREF>
								<OP VALUE="=" />
								<CONST VALUE="1" />
							</EXPR>
						</ASSERT>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<ASSERT>
							<EXPR>
								<VARREF>
									<NAME VALUE="VAR" />
								</VARREF>
								<OP VALUE="=" />
								<CONST VALUE="1" />
							</EXPR>
						</ASSERT>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<ASSERT>
							<EXPR>
								<VARREF>
									<NAME VALUE="VAR" />
								</VARREF>
								<OP VALUE="=" />
								<CONST VALUE="1" />
							</EXPR>
						</ASSERT>
					</STMT>
				</STEP>


			</SEQUENCE>
		</PROCTYPE>

	</MODULE>

</SPEC>

=== SnigdhaAthaiya/DFAS/AsyncDataAnalyzer/AsyncDataAnalyzer/oldModels/server.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SPEC SYSTEM "../dat/SPEC.dtd">
<SPEC>
	<MODULE>
		<MTYPE>
			<NAME VALUE="CSTART" />
			<NAME VALUE="SSTART" />
			<NAME VALUE="SET5" />
			<NAME VALUE="GET" />
			<NAME VALUE="GETACK" />
			<NAME VALUE="SHUTDOWN" />
		</MTYPE>
	</MODULE>
	<MODULE>
		<PROCTYPE>
			<NAME VALUE="START" />
			<SEQUENCE>
				<STEP>
					<DECLLIST>
						<DECL>
							<TYPENAME>
								<NUM />
							</TYPENAME>
							<IVAR>
								<NAME VALUE="V1" />
							</IVAR>
						</DECL>
						<DECL>
							<TYPENAME>
								<NUM />
							</TYPENAME>
							<IVAR>
								<NAME VALUE="V2" />
							</IVAR>
						</DECL>
						<DECL>
							<TYPENAME>
								<NUM />
							</TYPENAME>
							<IVAR>
								<NAME VALUE="VAL" />
							</IVAR>
						</DECL>
					</DECLLIST>
				</STEP>
				<STEP>
					<STMT>
						<ASSIGN>
							<VARREF>
								<NAME VALUE="V1" />
							</VARREF>
							<EXPR>
								<VARREF>
									<NAME VALUE="1,0" />
								</VARREF>
							</EXPR>
						</ASSIGN>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<ASSIGN>
							<VARREF>
								<NAME VALUE="V2" />
							</VARREF>
							<EXPR>
								<VARREF>
									<NAME VALUE="1,0" />
								</VARREF>
							</EXPR>
						</ASSIGN>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<ASSIGN>
							<VARREF>
								<NAME VALUE="VAL" />
							</VARREF>
							<EXPR>
								<VARREF>
									<NAME VALUE="1,0" />
								</VARREF>
							</EXPR>
						</ASSIGN>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<SEND>
							<NAME VALUE="CSTART" />
						</SEND>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<SEND>
							<NAME VALUE="SSTART" />
						</SEND>
					</STMT>
				</STEP>
			</SEQUENCE>
		</PROCTYPE>
	</MODULE>

	<MODULE>
		<PROCTYPE>
			<NAME VALUE="CLIENT" />
			<SEQUENCE>
				<STEP>
					<STMT>
						<RECEIVE>
							<NAME VALUE="CSTART" />
						</RECEIVE>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<SEND>
							<NAME VALUE="SET5" />
						</SEND>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<SEND>
							<NAME VALUE="GET" />
						</SEND>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<RECEIVE>
							<NAME VALUE="GETACK" />
						</RECEIVE>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<ASSIGN EVAL="TRUE" LABEL="L1" VARUSE="VAL">
							<VARREF>
								<NAME VALUE="V1" />
							</VARREF>
							<EXPR>
								<VARREF>
									<NAME VALUE="1,VAL" />
								</VARREF>
							</EXPR>
						</ASSIGN>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<SEND>
							<NAME VALUE="GET" />
						</SEND>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<RECEIVE>
							<NAME VALUE="GETACK" />
						</RECEIVE>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<ASSIGN EVAL="TRUE" LABEL="L2" VARUSE="VAL">
							<VARREF>
								<NAME VALUE="V2" />
							</VARREF>
							<EXPR>
								<VARREF>
									<NAME VALUE="1,VAL" />
								</VARREF>
							</EXPR>
						</ASSIGN>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<SEND>
							<NAME VALUE="SHUTDOWN" />
						</SEND>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<ASSERT EVAL="TRUE" VARUSE="V1,V2" LABEL="L3">
							<EXPR>
								<VARREF>
									<NAME VALUE="V1" />
								</VARREF>
								<OP VALUE="==" />
								<CONST VALUE="V2" />
							</EXPR>
						</ASSERT>
					</STMT>
				</STEP>
			</SEQUENCE>
		</PROCTYPE>
	</MODULE>

	<MODULE>
		<PROCTYPE>
			<NAME VALUE="SERVER" />
			<SEQUENCE>
				<STEP>
					<STMT>
						<RECEIVE>
							<NAME VALUE="SSTART" />
						</RECEIVE>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<DO>
							<OPTION>
								<SEQUENCE>
									<STEP>
										<STMT>
											<RECEIVE>
												<NAME VALUE="SHUTDOWN" />
											</RECEIVE>
										</STMT>
									</STEP>
									<STEP>
										<STMT>
											<BREAK />
										</STMT>
									</STEP>
								</SEQUENCE>
							</OPTION>
							<OPTION>
								<SEQUENCE>
									<STEP>
										<STMT>
											<RECEIVE>
												<NAME VALUE="SET5" />
											</RECEIVE>
										</STMT>
									</STEP>
									<STEP>
										<STMT>
											<ASSIGN>
												<VARREF>
													<NAME VALUE="VAL" />
												</VARREF>
												<EXPR>
													<VARREF>
														<NAME VALUE="1,5" />
													</VARREF>
												</EXPR>
											</ASSIGN>
										</STMT>
									</STEP>
								</SEQUENCE>
							</OPTION>
							<OPTION>
								<SEQUENCE>
									<STEP>
										<STMT>
											<RECEIVE>
												<NAME VALUE="GET" />
											</RECEIVE>
										</STMT>
									</STEP>
									<STEP>
										<STMT>
											<SEND>
												<NAME VALUE="GETACK" />
											</SEND>
										</STMT>
									</STEP>
								</SEQUENCE>
							</OPTION>
						</DO>
					</STMT>
				</STEP>
			</SEQUENCE>
		</PROCTYPE>
	</MODULE>
</SPEC>

=== SnigdhaAthaiya/DFAS/AsyncDataAnalyzer/AsyncDataAnalyzer/test/test3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SPEC SYSTEM "../dat/SPEC.dtd">
<SPEC>
	<MODULE>
		<MTYPE>
			<NAME VALUE="M1" />
			<NAME VALUE="M2" />
		</MTYPE>
	</MODULE>
	<MODULE>
		<PROCTYPE>
			<NAME VALUE="P1" />
			<SEQUENCE>
				<STEP>
					<DECLLIST>
						<DECL>
							<TYPENAME>
								<NUM />
							</TYPENAME>
							<IVAR>
								<NAME VALUE="VAR1" />
							</IVAR>
						</DECL>
						<DECL>
							<TYPENAME>
								<NUM />
							</TYPENAME>
							<IVAR>
								<NAME VALUE="VAR2" />
							</IVAR>
						</DECL>
					</DECLLIST>
				</STEP>
				<STEP>
					<STMT>
						<LABELEDST>
							<NAME VALUE="L1" />
						</LABELEDST>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<ASSIGN>
							<VARREF>
								<NAME VALUE="VAR1" />
							</VARREF>
							<EXPR>
								<VARREF>
									<NAME VALUE="1,3" />
								</VARREF>
							</EXPR>
						</ASSIGN>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<SEND>
							<NAME VALUE="M1" />
						</SEND>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<IF>
							<OPTION>
								<SEQUENCE>
									<STEP>
										<STMT>
											<RECEIVE>
												<NAME VALUE="M2" />
											</RECEIVE>
										</STMT>
									</STEP>
									<STEP>
										<STMT>
											<GOTO>
												<NAME VALUE="L1" />
											</GOTO>
										</STMT>
									</STEP>
								</SEQUENCE>
							</OPTION>
						</IF>
					</STMT>
				</STEP>
			</SEQUENCE>
		</PROCTYPE>

	</MODULE>

</SPEC>

=== SnigdhaAthaiya/DFAS/AsyncDataAnalyzer/AsyncDataAnalyzer/test/PrecisionCheck2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SPEC SYSTEM "../dat/SPEC.dtd">
<SPEC>
	<MODULE>
		<MTYPE>
			<NAME VALUE="M1" />
		</MTYPE>
	</MODULE>
	<MODULE>
		<PROCTYPE>
			<NAME VALUE="P1" />
			<SEQUENCE>
				<STEP>
					<DECLLIST>
						<DECL>
							<TYPENAME>
								<NUM />
							</TYPENAME>
							<IVAR>
								<NAME VALUE="X" />
							</IVAR>
						</DECL>
						<DECL>
							<TYPENAME>
								<NUM />
							</TYPENAME>
							<IVAR>
								<NAME VALUE="Y" />
							</IVAR>
						</DECL>
					</DECLLIST>
				</STEP>
				<STEP>
					<STMT>
						<ASSIGN>
							<VARREF>
								<NAME VALUE="X" />
							</VARREF>
							<EXPR>
								<VARREF>
									<NAME VALUE="1,1" />
								</VARREF>
							</EXPR>
						</ASSIGN>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<SEND>
							<NAME VALUE="M1" />
						</SEND>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<ASSERT LABEL="L1" VARUSE="X" EVAL="TRUE">
							<EXPR>
								<VARREF>
									<NAME VALUE="X" />
								</VARREF>
								<OP VALUE="=" />
								<CONST VALUE="1" />
							</EXPR>
						</ASSERT>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<SEND>
							<NAME VALUE="M1" />
						</SEND>
					</STMT>
				</STEP>
			</SEQUENCE>
		</PROCTYPE>

	</MODULE>

	<MODULE>
		<PROCTYPE>
			<NAME VALUE="P2" />
			<SEQUENCE>
				<STEP>
					<STMT>
						<RECEIVE>
							<NAME VALUE="M1" />
						</RECEIVE>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<ASSIGN>
							<VARREF>
								<NAME VALUE="Y" />
							</VARREF>
							<EXPR>
								<VARREF>
									<NAME VALUE="1,2" />
								</VARREF>
							</EXPR>
						</ASSIGN>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<ASSIGN>
							<VARREF>
								<NAME VALUE="X" />
							</VARREF>
							<EXPR>
								<VARREF>
									<NAME VALUE="1,Y" />
								</VARREF>
								<OP VALUE="+" />
								<VARREF>
									<NAME VALUE="1,-1" />
								</VARREF>
							</EXPR>
						</ASSIGN>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<RECEIVE>
							<NAME VALUE="M1" />
						</RECEIVE>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<ASSIGN>
							<VARREF>
								<NAME VALUE="X" />
							</VARREF>
							<EXPR>
								<VARREF>
									<NAME VALUE="1,3" />
								</VARREF>
							</EXPR>
						</ASSIGN>
					</STMT>
				</STEP>
			</SEQUENCE>
		</PROCTYPE>
	</MODULE>

</SPEC>
