=== SnigdhaAthaiya/DFAS/AsyncDataAnalyzer/AsyncDataAnalyzer/dat/SPEC.dtd
<!ELEMENT SPEC (MODULE+)>
<!ELEMENT MODULE (PROCTYPE|MTYPE|INIT)>
<!ELEMENT PROCTYPE (NAME , SEQUENCE)>
<!ELEMENT INIT (SEQUENCE)>
<!ELEMENT MTYPE (NAME+)>
<!ELEMENT SEQUENCE (STEP+)>
<!ELEMENT STEP (STMT | DECLLIST)>
<!ELEMENT DECLLIST (DECL+)>
<!ELEMENT DECL (TYPENAME, IVAR)>
<!ELEMENT TYPENAME (BIT | BOOL | NUM)>
<!ELEMENT BIT EMPTY>
<!ELEMENT BOOL EMPTY>
<!ELEMENT NUM EMPTY>
<!ELEMENT IVAR (NAME, (INDEX)?) >
<!ELEMENT VARREF (NAME, (EXPR | PROPACCESS)?)>
<!ELEMENT PROPACCESS (VARREF)>
<!ELEMENT SEND (NAME)>
<!ELEMENT RECEIVE (NAME)>
<!ELEMENT ASSIGN (VARREF, EXPR)>
<!ELEMENT EXPR ((VARREF | CONST), (OP, (VARREF | CONST))? )>
<!ELEMENT CONST EMPTY>
<!ELEMENT OP EMPTY>
<!ELEMENT NAME EMPTY>
<!ELEMENT INDEX EMPTY>
<!ELEMENT STMT (IF | DO | SEND | RECEIVE | ASSIGN | ELSE | BREAK | GOTO | LABELEDST | ASSERT | EXPR | ATOMIC)>
<!ELEMENT IF ((OPTION)+, (ELSE)?)>
<!ELEMENT DO ((OPTION)+, (ELSE)?)>
<!ELEMENT OPTION (SEQUENCE)>
<!ELEMENT ATOMIC (SEQUENCE)>
<!ELEMENT ELSE (SEQUENCE)>
<!ELEMENT BREAK EMPTY>
<!ELEMENT GOTO (NAME)>
<!ELEMENT LABELEDST (NAME)>
<!ELEMENT ASSERT (EXPR)>

<!ATTLIST CONST VALUE CDATA #REQUIRED>
<!ATTLIST OP VALUE CDATA #REQUIRED>
<!ATTLIST NAME VALUE CDATA #REQUIRED>
<!ATTLIST CONST VALUE CDATA #REQUIRED>
<!ATTLIST ASSIGN VARUSE CDATA #IMPLIED>
<!ATTLIST OPTION VARUSE CDATA #IMPLIED>
<!ATTLIST ASSERT VARUSE CDATA #IMPLIED>
<!ATTLIST ASSIGN LABEL CDATA "DEFAULTLABEL">
<!ATTLIST ASSERT LABEL CDATA "DEFAULTLABEL">
<!ATTLIST OPTION LABEL CDATA "DEFAULTLABEL">
<!ATTLIST ASSERT EVAL (TRUE|FALSE) "FALSE">
<!ATTLIST ASSIGN EVAL (TRUE|FALSE) "FALSE">

=== SnigdhaAthaiya/DFAS/AsyncDataAnalyzer/AsyncDataAnalyzer/test/test5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SPEC SYSTEM "../dat/SPEC.dtd">
<SPEC>
	<MODULE>
		<MTYPE>
			<NAME VALUE="M1" />
			<NAME VALUE="M2"/>
		</MTYPE>
	</MODULE>
	<MODULE>
		<PROCTYPE>
			<NAME VALUE="P1" />
			<SEQUENCE>
				<STEP>
					<DECLLIST>
						<DECL>
							<TYPENAME>
								<NUM />
							</TYPENAME>
							<IVAR>
								<NAME VALUE="VAR1" />
							</IVAR>
						</DECL>
					</DECLLIST>
				</STEP>
				<STEP>
					<STMT>
						<ATOMIC>
							<SEQUENCE>
								<STEP>
									<STMT>
										<ASSIGN>
											<VARREF>
												<NAME VALUE="VAR1" />
											</VARREF>
											<EXPR>
												<VARREF>
													<NAME VALUE="1,3" />
												</VARREF>
											</EXPR>
										</ASSIGN>
									</STMT>
								</STEP>
								<STEP>
									<STMT>
										<RECEIVE>
											<NAME VALUE="M1" />
										</RECEIVE>
									</STMT>
								</STEP>
								<STEP>
									<STMT>
										<SEND>
											<NAME VALUE="M2" />
										</SEND>
									</STMT>
								</STEP>
							</SEQUENCE>
						</ATOMIC>
					</STMT>
				</STEP>

			</SEQUENCE>
		</PROCTYPE>
	</MODULE>

</SPEC>

=== SnigdhaAthaiya/DFAS/AsyncDataAnalyzer/AsyncDataAnalyzer/corrected-models/dijkstra.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SPEC SYSTEM "../dat/SPEC.dtd">
<SPEC>
	<MODULE>
		<MTYPE>
			<NAME VALUE="SEMA0" />
			<NAME VALUE="SEMA1" />
		</MTYPE>
	</MODULE>



	<MODULE>
		<PROCTYPE>
			<NAME VALUE="DIJKSTRA" />
			<SEQUENCE>
				<STEP>
					<DECLLIST>
						<DECL>
							<TYPENAME>
								<NUM />
							</TYPENAME>
							<IVAR>
								<NAME VALUE="COUNT" />
							</IVAR>
						</DECL>
					</DECLLIST>
				</STEP>
				<STEP>
					<STMT>
						<ASSIGN>
							<VARREF>
								<NAME VALUE="COUNT" />
							</VARREF>
							<EXPR>
								<VARREF>
									<NAME VALUE="1,0" />
								</VARREF>
							</EXPR>
						</ASSIGN>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<DO>
							<OPTION>
								<SEQUENCE>
									<STEP>
										<STMT>
											<SEND>
												<NAME VALUE="SEMA0" />
											</SEND>
										</STMT>
									</STEP>
									<STEP>
										<STMT>
											<RECEIVE>
												<NAME VALUE="SEMA1" />
											</RECEIVE>
										</STMT>
									</STEP>
								</SEQUENCE>
							</OPTION>
						</DO>
					</STMT>
				</STEP>
			</SEQUENCE>
		</PROCTYPE>
	</MODULE>



	<MODULE>
		<PROCTYPE>
			<NAME VALUE="MONITOR" />
			<SEQUENCE>
				<STEP>
					<STMT>
						<ASSERT EVAL="TRUE" LABEL="L1" VARUSE="COUNT">
							<EXPR>
								<VARREF>
									<NAME VALUE="COUNT" />
								</VARREF>
								<OP VALUE="==" />
								<CONST VALUE="1 OR 0" />
							</EXPR>
						</ASSERT>
					</STMT>
				</STEP>
			</SEQUENCE>
		</PROCTYPE>
	</MODULE>

	<MODULE>
		<PROCTYPE>
			<NAME VALUE="USER1" />
			<SEQUENCE>
				<STEP>
					<STMT>
						<RECEIVE>
							<NAME VALUE="SEMA0" />
						</RECEIVE>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<ASSIGN EVAL="TRUE" VARUSE="COUNT" LABEL="L2">
							<VARREF>
								<NAME VALUE="COUNT" />
							</VARREF>
							<EXPR>
								<VARREF>
									<NAME VALUE="1,COUNT" />
								</VARREF>
								<OP VALUE="+" />
								<VARREF>
									<NAME VALUE="1,1" />
								</VARREF>
							</EXPR>
						</ASSIGN>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<ASSERT EVAL="TRUE" LABEL="L3" VARUSE="COUNT">
							<EXPR>
								<VARREF>
									<NAME VALUE="COUNT" />
								</VARREF>
								<OP VALUE="==" />
								<CONST VALUE="1" />
							</EXPR>
						</ASSERT>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<ASSIGN EVAL="TRUE" VARUSE="COUNT" LABEL="L4">
							<VARREF>
								<NAME VALUE="COUNT" />
							</VARREF>
							<EXPR>
								<VARREF>
									<NAME VALUE="1,COUNT" />
								</VARREF>
								<OP VALUE="+" />
								<VARREF>
									<NAME VALUE="1,-1" />
								</VARREF>
							</EXPR>
						</ASSIGN>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<SEND>
							<NAME VALUE="SEMA1" />
						</SEND>
					</STMT>
				</STEP>
			</SEQUENCE>
		</PROCTYPE>
	</MODULE>


	<MODULE>
		<PROCTYPE>
			<NAME VALUE="USER2" />
			<SEQUENCE>
				<STEP>
					<STMT>
						<RECEIVE>
							<NAME VALUE="SEMA0" />
						</RECEIVE>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<ASSIGN EVAL="TRUE" VARUSE="COUNT" LABEL="L5">
							<VARREF>
								<NAME VALUE="COUNT" />
							</VARREF>
							<EXPR>
								<VARREF>
									<NAME VALUE="1,COUNT" />
								</VARREF>
								<OP VALUE="+" />
								<VARREF>
									<NAME VALUE="1,1" />
								</VARREF>
							</EXPR>
						</ASSIGN>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<ASSERT EVAL="TRUE" LABEL="L6" VARUSE="COUNT">
							<EXPR>
								<VARREF>
									<NAME VALUE="COUNT" />
								</VARREF>
								<OP VALUE="==" />
								<CONST VALUE="1" />
							</EXPR>
						</ASSERT>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<ASSIGN EVAL="TRUE" VARUSE="COUNT" LABEL="L7">
							<VARREF>
								<NAME VALUE="COUNT" />
							</VARREF>
							<EXPR>
								<VARREF>
									<NAME VALUE="1,COUNT" />
								</VARREF>
								<OP VALUE="+" />
								<VARREF>
									<NAME VALUE="1,-1" />
								</VARREF>
							</EXPR>
						</ASSIGN>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<SEND>
							<NAME VALUE="SEMA1" />
						</SEND>
					</STMT>
				</STEP>
			</SEQUENCE>
		</PROCTYPE>
	</MODULE>
</SPEC>

=== SnigdhaAthaiya/DFAS/AsyncDataAnalyzer/AsyncDataAnalyzer/test/RecPExample2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SPEC SYSTEM "../dat/SPEC.dtd">
<SPEC>
	<MODULE>
		<MTYPE>
			<NAME VALUE="F" />
			<NAME VALUE="E" />
		</MTYPE>
	</MODULE>
	<MODULE>
		<PROCTYPE>
			<NAME VALUE="MAIN" />
			<SEQUENCE>
				<STEP>
					<DECLLIST>
						<DECL>
							<TYPENAME>
								<NUM />
							</TYPENAME>
							<IVAR>
								<NAME VALUE="X" />
							</IVAR>
						</DECL>
					</DECLLIST>
				</STEP>
				<STEP>
					<STMT>
						<SEND>
							<NAME VALUE="F" />
						</SEND>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<SEND>
							<NAME VALUE="" />
						</SEND>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<SEND>
							<NAME VALUE="F" />
						</SEND>
					</STMT>
				</STEP>

			</SEQUENCE>
		</PROCTYPE>

	</MODULE>

</SPEC>

=== SnigdhaAthaiya/DFAS/AsyncDataAnalyzer/AsyncDataAnalyzer/test/CriticalSection.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SPEC SYSTEM "../dat/SPEC.dtd">
<SPEC>
	<MODULE>
		<MTYPE>
			<NAME VALUE="REQ1" />
			<NAME VALUE="REQ2" />
			<NAME VALUE="ACK1" />
			<NAME VALUE="ACK2" />
			<NAME VALUE="REL1" />
			<NAME VALUE="REL2" />
		</MTYPE>
	</MODULE>

	<MODULE>
		<PROCTYPE>
			<NAME VALUE="P0" />
			<SEQUENCE>
				<STEP>
					<DECLLIST>
						<DECL>
							<TYPENAME>
								<NUM />
							</TYPENAME>
							<IVAR>
								<NAME VALUE="NCRITICAL" />
							</IVAR>
						</DECL>
					</DECLLIST>
				</STEP>
				<STEP>
					<STMT>
						<ASSIGN>
							<VARREF>
								<NAME VALUE="NCRITICAL" />
							</VARREF>
							<EXPR>
								<VARREF>
									<NAME VALUE="1,0" />
								</VARREF>
							</EXPR>
						</ASSIGN>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<DO>
							<OPTION>
								<SEQUENCE>
									<STEP>
										<STMT>
											<RECEIVE>
												<NAME VALUE="REQ1" />
											</RECEIVE>
										</STMT>
									</STEP>
									<STEP>
										<STMT>
											<SEND>
												<NAME VALUE="ACK1" />
											</SEND>
										</STMT>
									</STEP>
									<STEP>
										<STMT>
											<RECEIVE>
												<NAME VALUE="REL1" />
											</RECEIVE>
										</STMT>
									</STEP>
								</SEQUENCE>
							</OPTION>
							<OPTION>
								<SEQUENCE>
									<STEP>
										<STMT>
											<RECEIVE>
												<NAME VALUE="REQ2" />
											</RECEIVE>
										</STMT>
									</STEP>
									<STEP>
										<STMT>
											<SEND>
												<NAME VALUE="ACK2" />
											</SEND>
										</STMT>
									</STEP>
									<STEP>
										<STMT>
											<RECEIVE>
												<NAME VALUE="REL2" />
											</RECEIVE>
										</STMT>
									</STEP>
								</SEQUENCE>
							</OPTION>
						</DO>
					</STMT>
				</STEP>

			</SEQUENCE>
		</PROCTYPE>

	</MODULE>


	<MODULE>
		<PROCTYPE>
			<NAME VALUE="P1" />
			<SEQUENCE>
				<STEP>
					<STMT>
						<DO>
							<OPTION>
								<SEQUENCE>
									<STEP>
										<STMT>
											<SEND>
												<NAME VALUE="REQ1" />
											</SEND>
										</STMT>
									</STEP>
									<STEP>
										<STMT>
											<RECEIVE>
												<NAME VALUE="ACK1" />
											</RECEIVE>
										</STMT>
									</STEP>
									<STEP>
										<STMT>
											<ASSIGN EVAL="TRUE" VARUSE="NCRITICAL" LABEL="L1">
												<VARREF>
													<NAME VALUE="NCRITICAL" />
												</VARREF>
												<EXPR>
													<VARREF>
														<NAME VALUE="1,NCRITICAL" />
													</VARREF>
													<OP VALUE="+" />
													<VARREF>
														<NAME VALUE="1,1" />
													</VARREF>
												</EXPR>
											</ASSIGN>
										</STMT>
									</STEP>
									<STEP>
										<STMT>
											<ASSERT EVAL="TRUE" VARUSE="NCRITICAL" LABEL="L2">
												<EXPR>
													<VARREF>
														<NAME VALUE="NCRITICAL" />
													</VARREF>
													<OP VALUE="=" />
													<CONST VALUE="1" />
												</EXPR>
											</ASSERT>
										</STMT>
									</STEP>
									<STEP>
										<STMT>
											<ASSIGN EVAL="TRUE" VARUSE="NCRITICAL" LABEL="L3">
												<VARREF>
													<NAME VALUE="NCRITICAL" />
												</VARREF>
												<EXPR>
													<VARREF>
														<NAME VALUE="1,NCRITICAL" />
													</VARREF>
													<OP VALUE="+" />
													<VARREF>
														<NAME VALUE="1,-1" />
													</VARREF>
												</EXPR>
											</ASSIGN>
										</STMT>
									</STEP>
									<STEP>
										<STMT>
											<SEND>
												<NAME VALUE="REL1" />
											</SEND>
										</STMT>
									</STEP>
								</SEQUENCE>
							</OPTION>
						</DO>
					</STMT>
				</STEP>
			</SEQUENCE>
		</PROCTYPE>

	</MODULE>


	<MODULE>
		<PROCTYPE>
			<NAME VALUE="P2" />
			<SEQUENCE>
				<STEP>
					<STMT>
						<DO>
							<OPTION>
								<SEQUENCE>
									<STEP>
										<STMT>
											<SEND>
												<NAME VALUE="REQ2" />
											</SEND>
										</STMT>
									</STEP>
									<STEP>
										<STMT>
											<RECEIVE>
												<NAME VALUE="ACK2" />
											</RECEIVE>
										</STMT>
									</STEP>
									<STEP>
										<STMT>
											<ASSIGN EVAL="TRUE" VARUSE="NCRITICAL" LABEL="L4">
												<VARREF>
													<NAME VALUE="NCRITICAL" />
												</VARREF>
												<EXPR>
													<VARREF>
														<NAME VALUE="1,NCRITICAL" />
													</VARREF>
													<OP VALUE="+" />
													<VARREF>
														<NAME VALUE="1,1" />
													</VARREF>
												</EXPR>
											</ASSIGN>
										</STMT>
									</STEP>
									<STEP>
										<STMT>
											<ASSERT EVAL="TRUE" VARUSE="NCRITICAL" LABEL="L5">
												<EXPR>
													<VARREF>
														<NAME VALUE="NCRITICAL" />
													</VARREF>
													<OP VALUE="==" />
													<CONST VALUE="1" />
												</EXPR>
											</ASSERT>
										</STMT>
									</STEP>

									<STEP>
										<STMT>
											<ASSIGN EVAL="TRUE" VARUSE="NCRITICAL" LABEL="L6">
												<VARREF>
													<NAME VALUE="NCRITICAL" />
												</VARREF>
												<EXPR>
													<VARREF>
														<NAME VALUE="1,NCRITICAL" />
													</VARREF>
													<OP VALUE="+" />
													<VARREF>
														<NAME VALUE="1,-1" />
													</VARREF>
												</EXPR>
											</ASSIGN>
										</STMT>
									</STEP>
									<STEP>
										<STMT>
											<SEND>
												<NAME VALUE="REL2" />
											</SEND>
										</STMT>
									</STEP>
								</SEQUENCE>
							</OPTION>
						</DO>
					</STMT>
				</STEP>
			</SEQUENCE>
		</PROCTYPE>

	</MODULE>

</SPEC>

=== SnigdhaAthaiya/DFAS/AsyncDataAnalyzer/AsyncDataAnalyzer/test/test4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SPEC SYSTEM "../dat/SPEC.dtd">
<SPEC>
	<MODULE>
		<MTYPE>
			<NAME VALUE="M1" />
			<NAME VALUE="M2" />
		</MTYPE>
	</MODULE>
	<MODULE>
		<PROCTYPE>
			<NAME VALUE="P1" />
			<SEQUENCE>
				<STEP>
					<DECLLIST>
						<DECL>
							<TYPENAME>
								<NUM />
							</TYPENAME>
							<IVAR>
								<NAME VALUE="VAR1" />
							</IVAR>
						</DECL>
					</DECLLIST>
				</STEP>
				<STEP>
					<STMT>
						<ASSIGN>
							<VARREF>
								<NAME VALUE="VAR1" />
							</VARREF>
							<EXPR>
								<VARREF>
									<NAME VALUE="1,3" />
								</VARREF>
							</EXPR>
						</ASSIGN>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<SEND>
							<NAME VALUE="M1" />
						</SEND>
					</STMT>
				</STEP>
				
			</SEQUENCE>
		</PROCTYPE>
	</MODULE>
	<MODULE>
		<PROCTYPE>
			<NAME VALUE="P2" />
			<SEQUENCE>
				<STEP>
					<DECLLIST>
						<DECL>
							<TYPENAME>
								<NUM />
							</TYPENAME>
							<IVAR>
								<NAME VALUE="VAR2" />
							</IVAR>
						</DECL>
					</DECLLIST>
				</STEP>
				<STEP>
					<STMT>
						<ASSIGN>
							<VARREF>
								<NAME VALUE="VAR2" />
							</VARREF>
							<EXPR>
								<VARREF>
									<NAME VALUE="1,5" />
								</VARREF>
							</EXPR>
						</ASSIGN>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<RECEIVE>
							<NAME VALUE="M2" />
						</RECEIVE>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<ASSERT EVAL="TRUE" VARUSE="VAR1" LABEL="l1">
							<EXPR>
								<VARREF>
									<NAME VALUE="VAR1" />
								</VARREF>
								<OP VALUE="==" />
								<CONST VALUE="3" />
							</EXPR>
						</ASSERT>
					</STMT>
				</STEP>
				
			</SEQUENCE>
		</PROCTYPE>

	</MODULE>

</SPEC>

=== SnigdhaAthaiya/DFAS/AsyncDataAnalyzer/AsyncDataAnalyzer/test/CriticalSectionMod.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SPEC SYSTEM "../dat/SPEC.dtd">
<SPEC>
	<MODULE>
		<MTYPE>
			<NAME VALUE="REQ" />
			<NAME VALUE="ACK" />
			<NAME VALUE="REL" />			
		</MTYPE>
	</MODULE>

	<MODULE>
		<PROCTYPE>
			<NAME VALUE="P0" />
			<SEQUENCE>
				<STEP>
					<DECLLIST>
						<DECL>
							<TYPENAME>
								<NUM />
							</TYPENAME>
							<IVAR>
								<NAME VALUE="NCRITICAL" />
							</IVAR>
						</DECL>
					</DECLLIST>
				</STEP>
				<STEP>
					<STMT>
						<ASSIGN>
							<VARREF>
								<NAME VALUE="NCRITICAL" />
							</VARREF>
							<EXPR>
								<VARREF>
									<NAME VALUE="1,0" />
								</VARREF>
							</EXPR>
						</ASSIGN>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<DO>
							<OPTION>
								<SEQUENCE>
									<STEP>
										<STMT>
											<RECEIVE>
												<NAME VALUE="REQ" />
											</RECEIVE>
										</STMT>
									</STEP>
									<STEP>
										<STMT>
											<SEND>
												<NAME VALUE="ACK" />
											</SEND>
										</STMT>
									</STEP>
									<STEP>
										<STMT>
											<RECEIVE>
												<NAME VALUE="REL" />
											</RECEIVE>
										</STMT>
									</STEP>
								</SEQUENCE>
							</OPTION>							
						</DO>
					</STMT>
				</STEP>

			</SEQUENCE>
		</PROCTYPE>

	</MODULE>


	<MODULE>
		<PROCTYPE>
			<NAME VALUE="P1" />
			<SEQUENCE>
				<STEP>
					<STMT>
						<DO>
							<OPTION>
								<SEQUENCE>
									<STEP>
										<STMT>
											<SEND>
												<NAME VALUE="REQ" />
											</SEND>
										</STMT>
									</STEP>
									<STEP>
										<STMT>
											<RECEIVE>
												<NAME VALUE="ACK" />
											</RECEIVE>
										</STMT>
									</STEP>
									<STEP>
										<STMT>
											<ASSIGN EVAL="TRUE" VARUSE="NCRITICAL" LABEL="L1">
												<VARREF>
													<NAME VALUE="NCRITICAL" />
												</VARREF>
												<EXPR>
													<VARREF>
														<NAME VALUE="1,NCRITICAL" />
													</VARREF>
													<OP VALUE="+" />
													<VARREF>
														<NAME VALUE="1,1" />
													</VARREF>
												</EXPR>
											</ASSIGN>
										</STMT>
									</STEP>
									<STEP>
										<STMT>
											<ASSERT EVAL="TRUE" VARUSE="NCRITICAL" LABEL="L2">
												<EXPR>
													<VARREF>
														<NAME VALUE="NCRITICAL" />
													</VARREF>
													<OP VALUE="=" />
													<CONST VALUE="1" />
												</EXPR>
											</ASSERT>
										</STMT>
									</STEP>
									<STEP>
										<STMT>
											<ASSIGN EVAL="TRUE" VARUSE="NCRITICAL" LABEL="L3">
												<VARREF>
													<NAME VALUE="NCRITICAL" />
												</VARREF>
												<EXPR>
													<VARREF>
														<NAME VALUE="1,NCRITICAL" />
													</VARREF>
													<OP VALUE="+" />
													<VARREF>
														<NAME VALUE="1,-1" />
													</VARREF>
												</EXPR>
											</ASSIGN>
										</STMT>
									</STEP>
									<STEP>
										<STMT>
											<SEND>
												<NAME VALUE="REL" />
											</SEND>
										</STMT>
									</STEP>
								</SEQUENCE>
							</OPTION>
						</DO>
					</STMT>
				</STEP>
			</SEQUENCE>
		</PROCTYPE>

	</MODULE>


	<MODULE>
		<PROCTYPE>
			<NAME VALUE="P2" />
			<SEQUENCE>
				<STEP>
					<STMT>
						<DO>
							<OPTION>
								<SEQUENCE>
									<STEP>
										<STMT>
											<SEND>
												<NAME VALUE="REQ" />
											</SEND>
										</STMT>
									</STEP>
									<STEP>
										<STMT>
											<RECEIVE>
												<NAME VALUE="ACK" />
											</RECEIVE>
										</STMT>
									</STEP>
									<STEP>
										<STMT>
											<ASSIGN EVAL="TRUE" VARUSE="NCRITICAL" LABEL="L4">
												<VARREF>
													<NAME VALUE="NCRITICAL" />
												</VARREF>
												<EXPR>
													<VARREF>
														<NAME VALUE="1,NCRITICAL" />
													</VARREF>
													<OP VALUE="+" />
													<VARREF>
														<NAME VALUE="1,1" />
													</VARREF>
												</EXPR>
											</ASSIGN>
										</STMT>
									</STEP>
									<STEP>
										<STMT>
											<ASSERT EVAL="TRUE" VARUSE="NCRITICAL" LABEL="L5">
												<EXPR>
													<VARREF>
														<NAME VALUE="NCRITICAL" />
													</VARREF>
													<OP VALUE="==" />
													<CONST VALUE="1" />
												</EXPR>
											</ASSERT>
										</STMT>
									</STEP>

									<STEP>
										<STMT>
											<ASSIGN EVAL="TRUE" VARUSE="NCRITICAL" LABEL="L6">
												<VARREF>
													<NAME VALUE="NCRITICAL" />
												</VARREF>
												<EXPR>
													<VARREF>
														<NAME VALUE="1,NCRITICAL" />
													</VARREF>
													<OP VALUE="+" />
													<VARREF>
														<NAME VALUE="1,-1" />
													</VARREF>
												</EXPR>
											</ASSIGN>
										</STMT>
									</STEP>
									<STEP>
										<STMT>
											<SEND>
												<NAME VALUE="REL" />
											</SEND>
										</STMT>
									</STEP>
								</SEQUENCE>
							</OPTION>
						</DO>
					</STMT>
				</STEP>
			</SEQUENCE>
		</PROCTYPE>

	</MODULE>

</SPEC>

=== SnigdhaAthaiya/DFAS/AsyncDataAnalyzer/AsyncDataAnalyzer/oldModels/nursery_test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SPEC SYSTEM "../dat/SPEC.dtd">
<SPEC>
	<MODULE>
		<MTYPE>
			<NAME VALUE="START1" />
			<NAME VALUE="START2" />
			<NAME VALUE="DONE1" />
			<NAME VALUE="DONE2" />
		</MTYPE>
	</MODULE>
	<MODULE>
		<PROCTYPE>
			<NAME VALUE="TEST" />
			<SEQUENCE>
				<STEP>
					<DECLLIST>
						<DECL>
							<TYPENAME>
								<NUM />
							</TYPENAME>
							<IVAR>
								<NAME VALUE="JOBDONE1" />
							</IVAR>
						</DECL>
						<DECL>
							<TYPENAME>
								<NUM />
							</TYPENAME>
							<IVAR>
								<NAME VALUE="JOBDONE2" />
							</IVAR>
						</DECL>
					</DECLLIST>
				</STEP>
				<STEP>
					<STMT>
						<ASSIGN>
							<VARREF>
								<NAME VALUE="JOBDONE1" />
							</VARREF>
							<EXPR>
								<VARREF>
									<NAME VALUE="1,0" />
								</VARREF>
							</EXPR>
						</ASSIGN>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<ASSIGN>
							<VARREF>
								<NAME VALUE="JOBDONE2" />
							</VARREF>
							<EXPR>
								<VARREF>
									<NAME VALUE="1,0" />
								</VARREF>
							</EXPR>
						</ASSIGN>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<IF>
							<OPTION>
								<SEQUENCE>
									<STEP>
										<STMT>
											<SEND>
												<NAME VALUE="START1" />
											</SEND>
										</STMT>
									</STEP>
									<STEP>
										<STMT>
											<SEND>
												<NAME VALUE="START2" />
											</SEND>
										</STMT>
									</STEP>
								</SEQUENCE>
							</OPTION>
							<ELSE>
								<SEQUENCE>
									<STEP>
										<STMT>
											<SEND>
												<NAME VALUE="START2" />
											</SEND>
										</STMT>
									</STEP>
									<STEP>
										<STMT>
											<SEND>
												<NAME VALUE="START1" />
											</SEND>
										</STMT>
									</STEP>
								</SEQUENCE>
							</ELSE>
						</IF>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<IF>
							<OPTION>
								<SEQUENCE>
									<STEP>
										<STMT>
											<RECEIVE>
												<NAME VALUE="START1" />
											</RECEIVE>
										</STMT>
									</STEP>
									<STEP>
										<STMT>
											<RECEIVE>
												<NAME VALUE="START2" />
											</RECEIVE>
										</STMT>
									</STEP>
								</SEQUENCE>
							</OPTION>
							<ELSE>
								<SEQUENCE>
									<STEP>
										<STMT>
											<RECEIVE>
												<NAME VALUE="START2" />
											</RECEIVE>
										</STMT>
									</STEP>
									<STEP>
										<STMT>
											<RECEIVE>
												<NAME VALUE="START1" />
											</RECEIVE>
										</STMT>
									</STEP>
								</SEQUENCE>
							</ELSE>
						</IF>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<ASSERT LABEL="L1" VARUSE="JOBDONE1" EVAL="TRUE">
							<EXPR>
								<VARREF>
									<NAME VALUE="JOBDONE1" />
								</VARREF>
								<OP VALUE="==" />
								<CONST VALUE="1" />
							</EXPR>
						</ASSERT>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<ASSERT LABEL="L2" VARUSE="JOBDONE2" EVAL="TRUE">
							<EXPR>
								<VARREF>
									<NAME VALUE="JOBDONE2" />
								</VARREF>
								<OP VALUE="==" />
								<CONST VALUE="1" />
							</EXPR>
						</ASSERT>
					</STMT>
				</STEP>
			</SEQUENCE>
		</PROCTYPE>
	</MODULE>

	<MODULE>
		<PROCTYPE>
			<NAME VALUE="JOB1" />
			<SEQUENCE>
				<STEP>
					<STMT>
						<RECEIVE>
							<NAME VALUE="START1" />
						</RECEIVE>
					</STMT>
				</STEP>
				<!-- FAST PROCESS -->
				<STEP>
					<STMT>
						<ASSIGN>
							<VARREF>
								<NAME VALUE="JOBDONE1" />
							</VARREF>
							<EXPR>
								<VARREF>
									<NAME VALUE="1,1" />
								</VARREF>
							</EXPR>
						</ASSIGN>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<SEND>
							<NAME VALUE="DONE1" />
						</SEND>
					</STMT>
				</STEP>
			</SEQUENCE>
		</PROCTYPE>
	</MODULE>


	<MODULE>
		<PROCTYPE>
			<NAME VALUE="JOB2" />
			<SEQUENCE>
				<STEP>
					<STMT>
						<RECEIVE>
							<NAME VALUE="START2" />
						</RECEIVE>
					</STMT>
				</STEP>
				<!-- SLOW PROCESS -->
				<STEP>
					<STMT>
						<DO>
							<OPTION> <!-- NON-DETERMINISTIC DELAY -->
								<SEQUENCE>
									<STEP>
										<STMT>
											<EXPR>
												<CONST VALUE="1" />
											</EXPR>
										</STMT>
									</STEP>
								</SEQUENCE>
							</OPTION>
							<OPTION> 
								<SEQUENCE>
									<STEP>
										<STMT>
											<BREAK />
										</STMT>
									</STEP>
								</SEQUENCE>
							</OPTION>
						</DO>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<ASSIGN>
							<VARREF>
								<NAME VALUE="JOBDONE2" />
							</VARREF>
							<EXPR>
								<VARREF>
									<NAME VALUE="1,1" />
								</VARREF>
							</EXPR>
						</ASSIGN>
					</STMT>
				</STEP>
				<STEP>
					<STMT>
						<SEND>
							<NAME VALUE="DONE2" />
						</SEND>
					</STMT>
				</STEP>
			</SEQUENCE>
		</PROCTYPE>
	</MODULE>


</SPEC>
